[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/*,**/.next/cache/webpack/client-production/0.pack,**/.netlify/functions-internal/**/*,**/.next/_next/static/chunks/**/*"
  SECRETS_SCAN_ENABLED = "true" # Set to "false" if you want to disable secrets scanning entirely.